###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{    
    "email":"contador.manuel4@gmail.com",
    "password": "123456789"    
}

###
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{    
    "email":"contador.manuel4@gmail.com",
    "password": "123456789",
    "repassword":"123456789"    
}


###
GET http://localhost:3000/api/v1/auth/proteger
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2ODUzNDkwZTFmYTg4ZGU2YWJjY2VlZTMiLCJpYXQiOjE3NTAyOTQ2NzgsImV4cCI6MTc1MDI5NTU3OH0.OB9zKBchtqMqO_sOT3lLEXeEdbU-lwR4ICqKGJ1CG3s

  
###
GET http://localhost:3000/api/v1/links
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2ODU0YjBjYmRjYTM5YThiZDhmNTVkZjciLCJpYXQiOjE3NTA3ODU4NDYsImV4cCI6MTc1MDc4OTQ0Nn0.LbNMOuJMl2McPuYTNilit09K3rLuDxcmn_vki1xlzLo

###
GET http://localhost:3000/api/v1/links/jXMBHJ

###
GET http://localhost:3000/api/v1/links/<script>6854bbfaf14fde04101fafc3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2ODU0YjBjYmRjYTM5YThiZDhmNTVkZjciLCJpYXQiOjE3NTA0MDAwNzgsImV4cCI6MTc1MDQwMzY3OH0.GMHhWiWxB7nEP3BK92T3vieu1PVkYCea44XHZqqLPEo

###
DELETE http://localhost:3000/api/v1/links/6854bbfaf14fde04101fafc3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2ODU0YjBjYmRjYTM5YThiZDhmNTVkZjciLCJpYXQiOjE3NTA0MDAwNzgsImV4cCI6MTc1MDQwMzY3OH0.GMHhWiWxB7nEP3BK92T3vieu1PVkYCea44XHZqqLPEo


###
POST http://localhost:3000/api/v1/links
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2ODU0YjBjYmRjYTM5YThiZDhmNTVkZjciLCJpYXQiOjE3NTAzODMzMjcsImV4cCI6MTc1MDM4NDIyN30.Wil0wOE_WQq9h2VLR30Jbz_398tfVHFAXJlxNAJ3mu8
Content-Type: application/json

{    
    "longLink":"https://www.ejemplos.co/articulos/"
}


###
PATCH http://localhost:3000/api/v1/links/6854bbb8f14fde04101fafc1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2ODU0YjBjYmRjYTM5YThiZDhmNTVkZjciLCJpYXQiOjE3NTA3ODU4NDYsImV4cCI6MTc1MDc4OTQ0Nn0.LbNMOuJMl2McPuYTNilit09K3rLuDxcmn_vki1xlzLo
Content-Type: application/json

{    
    "longLink":"https://mongoosejs.com/"
}

###
PATCH http://localhost:3000/api/v1/links/6854bbb8f14fde04101fafc1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2ODU0YjBjYmRjYTM5YThiZDhmNTVkZjciLCJpYXQiOjE3NTA3ODU4NDYsImV4cCI6MTc1MDc4OTQ0Nn0.LbNMOuJMl2McPuYTNilit09K3rLuDxcmn_vki1xlzLo
Content-Type: application/json

{    
    "longLink":"https://www.eliteguias.com/guias/o/ot2/octopath-traveler-ii.php"
}


###
POST http://localhost:3000/user
Content-Type: text/plain

Hola mundo

###
POST http://localhost:3000/user
Content-Type: application/x-www-form-urlencoded

title=mi+primer+titulo&description=mi+descripcion+de+este+titulo





