###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{    
    "email":"contador.manuel3@gmail.com",
    "password": "123456789"    
}

###
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{    
    "email":"contador.manuel3@gmail.com",
    "password": "123456789",
    "repassword":"123456789"    
}


###
GET http://localhost:3000/api/v1/auth/proteger
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2ODUzNDkwZTFmYTg4ZGU2YWJjY2VlZTMiLCJpYXQiOjE3NTAyOTQ2NzgsImV4cCI6MTc1MDI5NTU3OH0.OB9zKBchtqMqO_sOT3lLEXeEdbU-lwR4ICqKGJ1CG3s





###
POST http://localhost:3000/user
Content-Type: text/plain

Hola mundo

###
POST http://localhost:3000/user
Content-Type: application/x-www-form-urlencoded

title=mi+primer+titulo&description=mi+descripcion+de+este+titulo





